/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabellenRouteImport } from './routes/tabellen'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as BarsRouteImport } from './routes/bars'
import { Route as IndexRouteImport } from './routes/index'

const TabellenRoute = TabellenRouteImport.update({
  id: '/tabellen',
  path: '/tabellen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const BarsRoute = BarsRouteImport.update({
  id: '/bars',
  path: '/bars',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bars': typeof BarsRoute
  '/profil': typeof ProfilRoute
  '/tabellen': typeof TabellenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bars': typeof BarsRoute
  '/profil': typeof ProfilRoute
  '/tabellen': typeof TabellenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bars': typeof BarsRoute
  '/profil': typeof ProfilRoute
  '/tabellen': typeof TabellenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bars' | '/profil' | '/tabellen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bars' | '/profil' | '/tabellen'
  id: '__root__' | '/' | '/bars' | '/profil' | '/tabellen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarsRoute: typeof BarsRoute
  ProfilRoute: typeof ProfilRoute
  TabellenRoute: typeof TabellenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tabellen': {
      id: '/tabellen'
      path: '/tabellen'
      fullPath: '/tabellen'
      preLoaderRoute: typeof TabellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bars': {
      id: '/bars'
      path: '/bars'
      fullPath: '/bars'
      preLoaderRoute: typeof BarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarsRoute: BarsRoute,
  ProfilRoute: ProfilRoute,
  TabellenRoute: TabellenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
