/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurnierRouteImport } from './routes/turnier'
import { Route as TippsRouteImport } from './routes/tipps'
import { Route as TabellenRouteImport } from './routes/tabellen'
import { Route as SpieleRouteImport } from './routes/spiele'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as BarsRouteImport } from './routes/bars'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'

const TurnierRoute = TurnierRouteImport.update({
  id: '/turnier',
  path: '/turnier',
  getParentRoute: () => rootRouteImport,
} as any)
const TippsRoute = TippsRouteImport.update({
  id: '/tipps',
  path: '/tipps',
  getParentRoute: () => rootRouteImport,
} as any)
const TabellenRoute = TabellenRouteImport.update({
  id: '/tabellen',
  path: '/tabellen',
  getParentRoute: () => rootRouteImport,
} as any)
const SpieleRoute = SpieleRouteImport.update({
  id: '/spiele',
  path: '/spiele',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const BarsRoute = BarsRouteImport.update({
  id: '/bars',
  path: '/bars',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bars': typeof BarsRoute
  '/profil': typeof ProfilRoute
  '/spiele': typeof SpieleRoute
  '/tabellen': typeof TabellenRoute
  '/tipps': typeof TippsRoute
  '/turnier': typeof TurnierRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bars': typeof BarsRoute
  '/profil': typeof ProfilRoute
  '/spiele': typeof SpieleRoute
  '/tabellen': typeof TabellenRoute
  '/tipps': typeof TippsRoute
  '/turnier': typeof TurnierRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bars': typeof BarsRoute
  '/profil': typeof ProfilRoute
  '/spiele': typeof SpieleRoute
  '/tabellen': typeof TabellenRoute
  '/tipps': typeof TippsRoute
  '/turnier': typeof TurnierRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bars'
    | '/profil'
    | '/spiele'
    | '/tabellen'
    | '/tipps'
    | '/turnier'
    | '/sitemap/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bars'
    | '/profil'
    | '/spiele'
    | '/tabellen'
    | '/tipps'
    | '/turnier'
    | '/sitemap/xml'
  id:
    | '__root__'
    | '/'
    | '/bars'
    | '/profil'
    | '/spiele'
    | '/tabellen'
    | '/tipps'
    | '/turnier'
    | '/sitemap/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarsRoute: typeof BarsRoute
  ProfilRoute: typeof ProfilRoute
  SpieleRoute: typeof SpieleRoute
  TabellenRoute: typeof TabellenRoute
  TippsRoute: typeof TippsRoute
  TurnierRoute: typeof TurnierRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turnier': {
      id: '/turnier'
      path: '/turnier'
      fullPath: '/turnier'
      preLoaderRoute: typeof TurnierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipps': {
      id: '/tipps'
      path: '/tipps'
      fullPath: '/tipps'
      preLoaderRoute: typeof TippsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabellen': {
      id: '/tabellen'
      path: '/tabellen'
      fullPath: '/tabellen'
      preLoaderRoute: typeof TabellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spiele': {
      id: '/spiele'
      path: '/spiele'
      fullPath: '/spiele'
      preLoaderRoute: typeof SpieleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bars': {
      id: '/bars'
      path: '/bars'
      fullPath: '/bars'
      preLoaderRoute: typeof BarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarsRoute: BarsRoute,
  ProfilRoute: ProfilRoute,
  SpieleRoute: SpieleRoute,
  TabellenRoute: TabellenRoute,
  TippsRoute: TippsRoute,
  TurnierRoute: TurnierRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
